mynftproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from home_dashboard.views import (
    home_view,
)

from user_dashboard.views import (
    register_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home"),
    path('blog/', include('user_dashboard.urls', "blog")),
    path('admin_blog/', include('admin_dashboard.urls', "admin_blog")),
    path('register/', register_view, name="register"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    # End Password Change Links
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user_dashboard/urls.py
from django.urls import path
from user_dashboard.views import(
    dashboard_view,
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    user_collections_view,
)

app_name = 'user_dashboard'

urlpatterns = [
    path('dashboard/', dashboard_view, name="dashboard"),
    path('create/', create_blog_view, name="create"),
    path('user_collections/', user_collections_view, name="user_collections"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
]

user_dashboard/models.py
from msilib.schema import Class
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver


# Registration and Creating User
class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have a username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

# Editing Email and Username and showing it immediately


class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(
        verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(
        verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

# Location to save Images


def upload_location(instance, filename, **kwargs):
    file_path = 'user_dashboard/{author_id}/{title}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename
    )
    return file_path

# Creating Blog Posts


class BlogPost(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False)
    body = models.TextField(max_length=500, null=False, blank=False)
    image = models.ImageField(
        upload_to=upload_location, null=False, blank=False)
    date_published = models.DateTimeField(
        auto_now_add=True, verbose_name="date published")
    date_uploaded = models.DateTimeField(
        auto_now=True, verbose_name="date published")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title

# DELETE IMAGE


@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)


def pre_save_blog_post_receiver(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = slugify(
            instance.author.username + "-" + instance.title)


pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

user_dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from user_dashboard.models import Account
from user_dashboard.models import BlogPost


# Registration Boxes
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        max_length=60, help_text='Required, add a valid email address')

    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2')


# Login and Authentication
class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        if not authenticate(email=email, password=password):
            raise forms.ValidationError('Invalid login')


# Editing Email and Username
class AccountUpdateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('email', 'username')

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            try:
                account = Account.objects.exclude(
                    pk=self.instance.pk).get(email=email)
            except Account.DoesNotExist:
                return email
            raise forms.ValidationError(
                'Email "%s" is already in use.' % email)

    def clean_username(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            try:
                account = Account.objects.exclude(
                    pk=self.instance.pk).get(username=username)
            except Account.DoesNotExist:
                return username
            raise forms.ValidationError(
                'Username "%s" is already in use.' % username)


class CreateBlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']


# EDIT BLOG POST
class UpdateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ('title', 'body', 'image')

    def save(self, commit=True):
        blog_post = self.instance
        blog_post.title = self.cleaned_data['title']
        blog_post.body = self.cleaned_data['body']

        if self.cleaned_data['image']:
            blog_post.image = self.cleaned_data['image']

        if commit:
            blog_post.save()

        return blog_post

user_dashboard/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import login, authenticate, logout
from user_dashboard.forms import AccountAuthenticationForm, RegistrationForm, AccountUpdateForm
from user_dashboard.models import BlogPost, Account
from user_dashboard.forms import CreateBlogPostForm
from user_dashboard.forms import UpdateBlogPostForm


# Create your views here.

# REGISTRATION FORM
def register_view(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect('home')
        else:
            context['registration_form'] = form
    else:
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'user_dashboard/register.html', context)

# LOGOUT FORM


def logout_view(request):
    logout(request)
    return redirect('home')

# LOGIN FORM


def login_view(request):
    context = {}

    user = request.user
    if user.is_authenticated:
        return redirect('home')

    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect('home')
    else:
        form = AccountAuthenticationForm()

    context['login_form'] = form
    return render(request, 'user_dashboard/login.html', context)

# EDIT EMAIL AND USERNAME


def account_view(request):
    if not request.user.is_authenticated:
        return redirect('login')

    context = {}

    if request.POST:
        form = AccountUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.initial = {
                "email": request.POST['email'],
                "username": request.POST['username'],
            }
            form.save()
            context['success_message'] = "Updated"
    else:
        form = AccountUpdateForm(
            initial={
                'email': request.user.email,
                'username': request.user.username,
            }
        )

    context['account_form'] = form

    # QUERYING BLOG POSTS
    blog_posts = BlogPost.objects.filter(author=request.user)
    context['blog_posts'] = blog_posts
    # END OF QUERYING BLOG POSTS

    return render(request, 'user_dashboard/account.html', context)

# USER MAIN DASHBOARD VIEW


def dashboard_view(request):
    return render(request, 'user_dashboard/dashboard.html')

# FORM TO CREATE BLOG


def create_blog_view(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()

    context['form'] = form
    return render(request, "user_dashboard/create_blog.html", context)

# MUST AUTHENTICATE VIEW


def must_authenticate_view(request):
    return render(request, 'user_dashboard/must_authenticate.html', {})


def detail_blog_view(request, slug):
    context = {}

    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['blog_post'] = blog_post

    return render(request, 'user_dashboard/detail_blog.html', context)


def edit_blog_view(request, slug):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("must_authenticate")

    blog_post = get_object_or_404(BlogPost, slug=slug)
    if request.POST:
        form = UpdateBlogPostForm(
            request.POST or None, request.FILES or None, instance=blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Updated successfully"
            blog_post = obj

    form = UpdateBlogPostForm(
        initial={"title": blog_post.title, "body": blog_post.body, "image": blog_post.image})

    context = {
        'form': form,
        'blog_post': blog_post,
    }

    context['form'] = form
    context['blog_post'] = blog_post

    return render(request, "user_dashboard/edit_blog.html", context)


# QUERYING User BLOG POSTS
def user_collections_view(request):
    if not request.user.is_authenticated:
        return redirect('login')

    context = {}

    blog_posts = BlogPost.objects.filter(author=request.user)
    context['blog_posts'] = blog_posts

    return render(request, 'user_dashboard/user_collections.html', context)

user_dashboard/templates/user_dashboard/account.html
{% extends 'index.html' %}

{% block title %}
    <title>Profile | {{request.user.username}}</title>
{% endblock title %}


{% block content %}

<form class="form-signin" method="POST">{% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Change Email/Username</h1>

    <input type="email" name="email" class="form-control" id="inputEmail" placeholder="Email address" autofocus value={{account_form.initial.email}}>
    
    <input type="text" name="username" class="form-control" id="inputUsername" placeholder="Username" value={{account_form.initial.username}}>

    {% for field in account_form %}
        {% for error in field.errors %}
            <p class="red_error">{{error}}</p>
        {% endfor %}
    {% endfor %}

    {% if account_form.non_field_errors %}
        <p class="red_error">{{account_form.non_field_errors}}</p>
    {% endif %}

    {% if success_message %}
        <p class="green_success">{{success_message}}</p>
    {% endif %}
    <br>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Save Changes</button>
    <br>
    <br>
    <a class="me-3 py-2" href="{% url 'password_change' %}">Change Password</a>
</form>

{% endblock content %}

user_dashboard/templates/user_dashboard/create_blog.html
{% extends 'index.html' %}

{% block title %}
    <title>Create Blog | {{request.user.username}}</title>
{% endblock title %}


{% block content %}


<div>
    <h1>Create a new blog</h1>
    <p>This is a paragraph</p>
</div>

<div class="container text-center">
    <form class="create_form" method="post" enctype="multipart/form-data">{% csrf_token %}
        <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
        <br>
        <input class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="Body" required >
        <br>
        <input type="file" name="image" id="id_image" accept="image/*" required >
        <br>
        <br>

        <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Post</button>
    </form>
</div>


{% endblock content %}

user_dashboard/templates/user_dashboard/dashboard.html
{% extends 'index.html' %}

{% block title %}
    <title>My Dashboard | {{request.user.username}}</title>
{% endblock title %}


{% block content %}

<div class="container">
    <h1>User Dashboard</h1>
    <div>
        <h1>Account Balance</h1>
        <p>This is a paragraph</p>
    </div>

    <div>
        <h1>Total Sold</h1>
        <p>This is a paragraph</p>
    </div>

    <div>
        <h1>Total Withdrawal</h1>
        <p>This is a paragraph</p>
    </div>

    <div>
        <h1>Total Purchased</h1>
        <p>This is a paragraph</p>
    </div>

    <div>
        <h1>Referral Bonus</h1>
        <p>This is a paragraph</p>
    </div>
</div>


{% endblock content %}

user_dashboard/templates/user_dashboard/detail_blog.html
{% extends 'index.html' %}

{% block title %}
    <title>{{title}} | {{request.user.username}}</title>
{% endblock title %}


{% block content %}


<div>
    <h1>{{blog_post.title}}</h1>
    <p>This is a paragraph</p>
</div>

<div class="container">
    <div class="row">
        <div class="card m-auto">
            <img class="card-img-top" src="{{blog_post.image.url}}">
            <div class="card-body my-2">
                <h2 class="card-title">{{blog_post.title}}</h2>
                <p class="card-text">{{blog_post.body}}</p>
                {% if blog_post.author == request.user %}
                <a href="{% url 'user_dashboard:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
                {% elif request.user.is_admin %}
                <a href="{% url 'user_dashboard:edit' blog_post.slug %}" class="btn btn-primary">Update as Admin</a>
                {% endif %}
                <a href="#" class="btn btn-success">Purchase</a>
            </div>
            <div class="card-footer text-muted">
                <p class="card-text">Updated on {{blog_post.date_updated}} by {{blog_post.author}} </p>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

user_dashboard/templates/user_dashboard/edit_blog.html
{% extends 'index.html' %}

{% block title %}
    <title>Edit NFT | {{request.user.username}}</title>
{% endblock title %}


{% block content %}


<div>
    <h1>Edit NFT</h1>
</div>

<div class="container text-center">
    <form class="create_form" method="post" enctype="multipart/form-data">{% csrf_token %}
        <input class="form-control" type="text" name="title" id="id_title" value="{{blog_post.title}}">
        <br>
        <input class="form-control" rows="10" type="text" name="body" id="id_body" value="{{blog_post.body}}">
        <br>
        <div class="form-group image-group" id="id_image_group">
            <img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
            <div class="middle">
                <div class="text">Change Image</div>
            </div>
        </div>
        <br>
        <input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
        <br>

        {% for field in form %}
            {% for error in field.errors %}
            <p>{{error}}</p>
            {% endfor %}
        {% endfor %}
        {% if success_message %}
        <p class="green_success">{{success_message}}</p>
        {% endif %}
        {% if form.non_field_errors %}
        <p>{{form.non_field_errors}}</p>
        {% endif %}
        <br>

        <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
    </form>
</div>


{% endblock content %}

user_dashboard/templates/user_dashboard/login.html
{% extends 'index.html' %}
{% load static %}


{% block title %}
    <title>Login | {{request.user.username}}</title>
{% endblock title %}



{% block content %}

<form class="form-signin" method="POST">{% csrf_token %}
    <div class="d-flex flex-column pb-3">
        <img class="img-fluid mx-auto" src="{% static '2.jpeg' %}" alt='codingwithfrankie' width="72" height='72'>
    </div>
    <h1 class="h3 mb-3 fw-normal">Login</h1>

    <input type="email" name="email" class="form-control" id="inputEmail" placeholder="Email address" required autofocus>

    <input type="password" name="password" class="form-control" id="inputPassword" placeholder="Password" required>

    {% for field in login_form %}
        {% for error in field.errors %}
            <p>{{error}}</p>
        {% endfor %}
    {% endfor %}

    {% if login_form.non_field_errors %}
        <p>{{login_form.non_field_errors}}</p>
    {% endif %}

    <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
    <br>
    <br>
    <a class="me-3 py-2" href="{% url 'password_reset' %}">Reset Password</a>
</form>


{% endblock content %}

user_dashboard/templates/user_dashboard/must_authenticate.html
{% extends 'index.html' %}
{% load static %}


{% block title %}
    <title>Access Denied | Log In</title>
{% endblock title %}


{% block content %}

<div class="container">
    <div class="d-flex flex-column">
        <h4>Must authenticate to view this page</h4>
        <p><a href="{% url 'register' %}">Register</a></p>
        <p><a href="{% url 'login' %}">Login</a></p>
    </div>
</div>

{% endblock content %}

user_dashboard/templates/user_dashboard/register.html
{% extends 'index.html' %}

{% load static %}

{% block title %}
    <title>Create an account | {{request.user.username}}</title>
{% endblock title %}



{% block content %}

<form class="form-signin" method="POST">{% csrf_token %}
    <div class="d-flex flex-column pb-3">
        <img class="img-fluid mx-auto" src="{% static '2.jpeg' %}" alt='codingwithfrankie' width="72" height='72'>
    </div>
    <h1 class="h3 mb-3 fw-normal">Register</h1>

    <input type="email" name="email" class="form-control" id="inputEmail" placeholder="Email address" required autofocus>
    
    <input type="text" name="username" class="form-control" id="inputUsername" placeholder="Username" required>

    <input type="password" name="password1" class="form-control" id="inputPassword1" placeholder="Password" required>

    <input type="password" name="password2" class="form-control" id="inputPassword2" placeholder="Confirm password" required>

    {% for field in registration_form %}
        {% for error in field.errors %}
            <p class="red_error">{{error}}</p>
        {% endfor %}
    {% endfor %}

    {% if registration_form.non_field_errors %}
        <p class="red_error">{{registration_form.non_field_errors}}</p>
    {% endif %}

    <br>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
</form>


{% endblock content %}

user_dashboard/templates/user_dashboard/user_collections.html
{% extends 'index.html' %}

{% block title %}
    <title>My Collections | {{request.user.username}}</title>
{% endblock title %}


{% block content %}

<div class="container">
    <h3>My Collections</h3>
    {% if blog_posts %}
    <ul>
        {% for post in blog_posts %}
        <a href="{% url 'user_dashboard:detail' post.slug %}">
            <li class="list-group-item">{{post.image}} | {{post.title}} | {{post.author}}</li>
        </a>
        {% endfor %}
    </ul>
    {% else %}
    <p>You do not have any NFT collections. Mint an NFT <a href="{% url 'user_dashboard:create' %}">now</a>.</p>
    {% endif %}
</div>

{% endblock content %}