admin_dashboard/urls.py
from django.urls import path
from admin_dashboard.views import (
    admin_dashboard_view,
    nft_view,
    transaction_view,
    withdrawal_view,
)

app_name = 'admin_dashboard'

urlpatterns = [
    path('admin_dashboard/', admin_dashboard_view, name="admin_dashboard"),
    path('nft/', nft_view, name="nft"),
    path('transaction/', transaction_view, name="transaction"),
    path('withdrawal/', withdrawal_view, name="withdrawal"),
]

mynftproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from home_dashboard.views import (
    home_view,
)

from user_dashboard.views import (
    register_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home"),
    path('blog/', include('user_dashboard.urls', "blog")),
    path('admin_blog/', include('admin_dashboard.urls', "admin_blog")),
    path('register/', register_view, name="register"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    # End Password Change Links
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user_dashboard/urls.py
from django.urls import path
from user_dashboard.views import(
    dashboard_view,
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    user_collections_view,
)

app_name = 'user_dashboard'

urlpatterns = [
    path('dashboard/', dashboard_view, name="dashboard"),
    path('create/', create_blog_view, name="create"),
    path('user_collections/', user_collections_view, name="user_collections"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
]

templates/snippets/footer.html
<style type="text/css">
    .footer{
        min-height: 100px;
</style>

<div class="d-flex flex-row align-items-center footer -auto">
    <p class="m-auto">Coding with Frankie... | 2022</p>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

templates/snippets/links.html
{% load static %}

{% comment %} Required meta tags {% endcomment %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% comment %} END OF Required meta tags {% endcomment %}

{% comment %} CSS FILES {% endcomment %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
{% comment %} END OF CSS FILES {% endcomment %}

{% comment %} JS Files {% endcomment %}
<script src="{% static 'assets/js/main.js' %}"></script>
{% comment %} End of Js files {% endcomment %}

templates/snippets/nav.html
{% load static %}

<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="{% url 'home' %}" class="d-flex align-items-center text-dark text-decoration-none">
      WEBSITE LOGO
    {% comment %} If Logged in {% endcomment %}
        {% if request.user.is_authenticated %}
             | Hello, {{request.user.username}}
        {% endif %}
    {% comment %} End of If Logged in {% endcomment %}
    </a>
    
    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
{% comment %} If User {% endcomment %}
    {% if request.user.is_authenticated == True and request.user.is_admin == False %}
    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'home' %}">Home</a>
    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'user_dashboard:dashboard' %}">My Dashboard</a>
    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'user_dashboard:user_collections' %}">My Collections</a>
    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'account' %}">My Profile</a>
    <a class="me-3 py-2 btn btn-outline-danger" href="{% url 'logout' %}">Logout</a>
{% comment %} End of If User {% endcomment %}
{% comment %} If Admin {% endcomment %}
    {% elif request.user.is_admin %}
    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'home' %}">Home</a>
    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'account' %}">My Profile</a>
    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'admin_dashboard:admin_dashboard' %}">Users</a>
    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'admin_dashboard:nft' %}">All Collections</a>
    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'admin_dashboard:transaction' %}">Transactions</a>
    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'admin_dashboard:withdrawal' %}">Withdrawals</a>
    <a class="me-3 py-2 btn btn-outline-danger" href="{% url 'logout' %}">Logout</a>
{% comment %} End of If Admin {% endcomment %}
{% comment %} If not logged in {% endcomment %}
    {% else %}
    <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'login' %}">Login</a>
    <a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
    {% endif %}
{% comment %} End of If {% endcomment %}
    </nav>
</div>